R_GLAB_386.4.4 Aggregations

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Category': ['A', 'A', 'B', 'B', 'A', 'B','A','B'],
    'Value': [10, 15, 20, 25, 30, 35,40,50],
    'Fee' :[20000,25000,26000,22000,24000,35000,4000,5600],
    'Duration':['30day','40days','35days','40days','60days','60days','50days','60days'],
    'Discount':[1000,2300,1200,2500,2000,2000,500,600]
}

In [4]:
df = pd.DataFrame(data)
print(df.head())

  Category  Value    Fee Duration  Discount
0        A     10  20000    30day      1000
1        A     15  25000   40days      2300
2        B     20  26000   35days      1200
3        B     25  22000   40days      2500
4        A     30  24000   60days      2000

In [5]:
# calculate the total sum of the Value column using the aggregate function
total_sum = df['Value'].agg('sum')
print(total_sum)

225

In [6]:
total_sum1 = df[['Value']].agg('sum')
print(f'total sum: {total_sum}')

total sum: 225

In [7]:
df['Value'].agg('cumsum')

0     10
1     25
2     45
3     70
4    100
5    135
6    175
7    225
Name: Value, dtype: int64

In [8]:
df[['Value']].agg('cumsum')

   Value
0     10
1     25
2     45
3     70
4    100
5    135
6    175
7    225

In [ ]:
# use both the agg and alternative to find: mean, max, count

In [9]:
# Using agg
value_stats_agg = df['Value'].agg(['mean', 'max', 'count'])
print("Using agg:")
print(value_stats_agg)

# Alternative using built-in methods
value_stats_alt = {
    'mean': df['Value'].mean(),
    'max': df['Value'].max(),
    'count': df['Value'].count()
}
print("Alternative:")
print(value_stats_alt)

Using agg:
mean     28.125
max      50.000
count     8.000
Name: Value, dtype: float64
Alternative:
{'mean': np.float64(28.125), 'max': np.int64(50), 'count': np.int64(8)}

In [12]:
# OR
mean1 = df['Value'].agg('mean')
print(f'mean: {mean1}')
mean2 = df[['Value']].mean()
print(f'mean: {mean2}')

mean: 28.125
mean: Value    28.125
dtype: float64

In [13]:
max1 = df['Value'].agg('max')
print(f'max: {max1}')
max2 = df[['Value']].max()
print(f'max: {max2}')

max: 50
max: Value    50
dtype: int64

In [14]:
count1 = df['Value'].agg('count')
print(count1)

count2 = df[['Value']].count()
print(count2)

8
Value    8
dtype: int64

Multiple Aggregations

In [16]:
result = df[['Fee', 'Discount']].agg('sum')
result

Fee         161600
Discount     12100
dtype: int64

In [17]:
result = df[['Fee', 'Discount']].sum()
result

Fee         161600
Discount     12100
dtype: int64

In [19]:
result = df[['Fee', 'Discount']].agg(['min', 'max', 'mean'])
result

          Fee  Discount
min    4000.0     500.0
max   35000.0    2500.0
mean  20200.0    1512.5

In [22]:
result_group = df.groupby('Category')[['Value', 'Fee', 'Discount']].agg(['sum', 'mean', 'min'])
result_group

         Value               Fee                Discount
           sum   mean min    sum     mean   min      sum    mean  min
Category
A           95  23.75  10  73000  18250.0  4000     5800  1450.0  500
B          130  32.50  20  88600  22150.0  5600     6300  1575.0  600