GLAB 386.3.16: Converting Date Like string

In [1]:
import pandas as pd
import numpy as np

In [2]:
dateRange = pd.date_range(start = "07-01-2023", end = "07-31-2025")
dateRange

DatetimeIndex(['2023-07-01', '2023-07-02', '2023-07-03', '2023-07-04',
               '2023-07-05', '2023-07-06', '2023-07-07', '2023-07-08',
               '2023-07-09', '2023-07-10',
               ...
               '2025-07-22', '2025-07-23', '2025-07-24', '2025-07-25',
               '2025-07-26', '2025-07-27', '2025-07-28', '2025-07-29',
               '2025-07-30', '2025-07-31'],
              dtype='datetime64[us]', length=762, freq='D')

In [3]:
dateRange = pd.date_range(start="01-01-2023", end="07-31-2025", freq="6min")
dateRange

DatetimeIndex(['2023-01-01 00:00:00', '2023-01-01 00:06:00',
               '2023-01-01 00:12:00', '2023-01-01 00:18:00',
               '2023-01-01 00:24:00', '2023-01-01 00:30:00',
               '2023-01-01 00:36:00', '2023-01-01 00:42:00',
               '2023-01-01 00:48:00', '2023-01-01 00:54:00',
               ...
               '2025-07-30 23:06:00', '2025-07-30 23:12:00',
               '2025-07-30 23:18:00', '2025-07-30 23:24:00',
               '2025-07-30 23:30:00', '2025-07-30 23:36:00',
               '2025-07-30 23:42:00', '2025-07-30 23:48:00',
               '2025-07-30 23:54:00', '2025-07-31 00:00:00'],
              dtype='datetime64[us]', length=226081, freq='6min')

In [6]:
dateRange = pd.date_range(start="2023-07-01", end="2025-07-31", freq="8min")
print(dateRange)

DatetimeIndex(['2023-07-01 00:00:00', '2023-07-01 00:08:00',
               '2023-07-01 00:16:00', '2023-07-01 00:24:00',
               '2023-07-01 00:32:00', '2023-07-01 00:40:00',
               '2023-07-01 00:48:00', '2023-07-01 00:56:00',
               '2023-07-01 01:04:00', '2023-07-01 01:12:00',
               ...
               '2025-07-30 22:48:00', '2025-07-30 22:56:00',
               '2025-07-30 23:04:00', '2025-07-30 23:12:00',
               '2025-07-30 23:20:00', '2025-07-30 23:28:00',
               '2025-07-30 23:36:00', '2025-07-30 23:44:00',
               '2025-07-30 23:52:00', '2025-07-31 00:00:00'],
              dtype='datetime64[us]', length=136981, freq='8min')

In [7]:
pd.date_range(start = "01-01-2023", end = "07-31-2025", freq='B')

DatetimeIndex(['2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05',
               '2023-01-06', '2023-01-09', '2023-01-10', '2023-01-11',
               '2023-01-12', '2023-01-13',
               ...
               '2025-07-18', '2025-07-21', '2025-07-22', '2025-07-23',
               '2025-07-24', '2025-07-25', '2025-07-28', '2025-07-29',
               '2025-07-30', '2025-07-31'],
              dtype='datetime64[us]', length=674, freq='B')

In [8]:
pd.date_range(start = "01-01-2023", end = "07-31-2025", freq='W')

DatetimeIndex(['2023-01-01', '2023-01-08', '2023-01-15', '2023-01-22',
               '2023-01-29', '2023-02-05', '2023-02-12', '2023-02-19',
               '2023-02-26', '2023-03-05',
               ...
               '2025-05-25', '2025-06-01', '2025-06-08', '2025-06-15',
               '2025-06-22', '2025-06-29', '2025-07-06', '2025-07-13',
               '2025-07-20', '2025-07-27'],
              dtype='datetime64[us]', length=135, freq='W-SUN')

In [9]:
dateRange = pd.date_range(start ="01-01-2023", periods=6, freq ="2ME")
print(dateRange)

DatetimeIndex(['2023-01-31', '2023-03-31', '2023-05-31', '2023-07-31',
               '2023-09-30', '2023-11-30'],
              dtype='datetime64[us]', freq='2ME')

In [10]:
dateRange = pd.date_range(start ="01-01-2023", periods=6, tz="Asia/Tokyo")
print(dateRange)

DatetimeIndex(['2023-01-01 00:00:00+09:00', '2023-01-02 00:00:00+09:00',
               '2023-01-03 00:00:00+09:00', '2023-01-04 00:00:00+09:00',
               '2023-01-05 00:00:00+09:00', '2023-01-06 00:00:00+09:00'],
              dtype='datetime64[us, Asia/Tokyo]', freq='D')

In [11]:
import pandas as pd
import numpy as np

In [12]:
# Set a specific start date and number of periods (days)
start_date = '2023-01-01'
num_days = 30

# Generate a date range
date_range = pd.date_range(start=start_date, periods=num_days, freq='D')

# Simulate stock prices for each date
np.random.seed(42)
stock_prices = np.random.normal(loc=100, scale=5, size=num_days).round(2)

# Create a DataFrame
stock_df = pd.DataFrame({'Date': date_range, 'StockPrice': stock_prices})

# Display the DataFrame
print(stock_df)

         Date  StockPrice
0  2023-01-01      102.48
1  2023-01-02       99.31
2  2023-01-03      103.24
3  2023-01-04      107.62
4  2023-01-05       98.83
5  2023-01-06       98.83
6  2023-01-07      107.90
7  2023-01-08      103.84
8  2023-01-09       97.65
9  2023-01-10      102.71
10 2023-01-11       97.68
11 2023-01-12       97.67
12 2023-01-13      101.21
13 2023-01-14       90.43
14 2023-01-15       91.38
15 2023-01-16       97.19
16 2023-01-17       94.94
17 2023-01-18      101.57
18 2023-01-19       95.46
19 2023-01-20       92.94
20 2023-01-21      107.33
21 2023-01-22       98.87
22 2023-01-23      100.34
23 2023-01-24       92.88
24 2023-01-25       97.28
25 2023-01-26      100.55
26 2023-01-27       94.25
27 2023-01-28      101.88
28 2023-01-29       97.00
29 2023-01-30       98.54

In [13]:
import pandas as pd
import datetime

In [14]:
timestamp_str = pd.Timestamp('2023-01-15 10:30:00')
print(f"Timestamp from string: {timestamp_str}")
print(f"Type of timestamp_str: {type(timestamp_str)}\n")

Timestamp from string: 2023-01-15 10:30:00
Type of timestamp_str: <class 'pandas.Timestamp'>

In [16]:
dt_object = datetime.datetime(2024, 7, 21, 14, 45, 10)
timestamp_dt = pd.Timestamp(dt_object)
print(f"Timestamp from datetime object: {timestamp_dt}")
print(f"Type of timestamp_dt: {type(timestamp_dt)}\n")

Timestamp from datetime object: 2024-07-21 14:45:10
Type of timestamp_dt: <class 'pandas.Timestamp'>

In [17]:
timestamp_components = pd.Timestamp(year=2025, month=3, day=1, hour=9, minute=0, second=0)
print(f"Timestamp from components: {timestamp_components}")
print(f"Type of timestamp_components: {type(timestamp_components)}\n")

Timestamp from components: 2025-03-01 09:00:00
Type of timestamp_components: <class 'pandas.Timestamp'>

In [18]:
print(f"Year: {timestamp_components.year}")
print(f"Month: {timestamp_components.month}")
print(f"Day: {timestamp_components.day}")
print(f"Hour: {timestamp_components.hour}")
print(f"Minute: {timestamp_components.minute}")
print(f"Second: {timestamp_components.second}")
print(f"Day of week (0=Monday, 6=Sunday): {timestamp_components.dayofweek}")
print(f"Name of the day: {timestamp_components.day_name()}")
print(f"Is it a leap year?: {timestamp_components.is_leap_year}\n")

Year: 2025
Month: 3
Day: 1
Hour: 9
Minute: 0
Second: 0
Day of week (0=Monday, 6=Sunday): 5
Name of the day: Saturday
Is it a leap year?: False

In [1]:
import pandas as pd
df = pd.DataFrame({
    'patientID':[101,23,48,49],
    'name': ['alice','bob','charlie','keyla'],
    'date_of_birth': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']
})

In [2]:
print("\n====== before convert ============")
print("Original Date Strings:")
print(df)
print("Data Type of date_of_birth column: ", df['date_of_birth'].dtype)
print(type(df["date_of_birth"]))
print(df['date_of_birth'])

====== before convert ============
Original Date Strings:
   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-01-02
2         48  charlie    2023-01-03
3         49    keyla    2023-01-04
Data Type of date_of_birth column:  str
<class 'pandas.Series'>
0    2023-01-01
1    2023-01-02
2    2023-01-03
3    2023-01-04
Name: date_of_birth, dtype: str

In [3]:
print("\n======= after convert============")

======= after convert============

In [4]:
df['date_of_birth'] = pd.to_datetime(df['date_of_birth'], format='mixed', dayfirst=True, errors='coerce')

print("Data Type of date_of_birth column: ", df['date_of_birth'].dtype)

print("\nConverted DateTime Objects:")
print(df)

Data Type of date_of_birth column:  datetime64[us]

Converted DateTime Objects:
   patientID     name date_of_birth
0        101    alice    2023-01-01
1         23      bob    2023-02-01
2         48  charlie    2023-03-01
3         49    keyla    2023-04-01

In [7]:
import pandas as pd
import ssl
from io import StringIO
url='https://raw.githubusercontent.com/bprasad26/lwd/master/data/tesla_stock_prices.csv'
# Assuming the date format is YYYY-MM-DD
import urllib.request

context = ssl._create_unverified_context()
with urllib.request.urlopen(url, context=context) as response:
    csv_data = response.read().decode("utf-8")

tesla_df = pd.read_csv(StringIO(csv_data), parse_dates=["Date"], date_format="%Y-%m-%d")
# Display the DataFrame

tesla_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900
...,...,...,...,...,...,...,...
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500
1787,2017-08-03,345.329987,350.000000,343.149994,347.089996,347.089996,13535000
1788,2017-08-04,347.000000,357.269989,343.299988,356.910004,356.910004,9198400
1789,2017-08-07,357.350006,359.480011,352.750000,355.170013,355.170013,6276900
1790,2017-08-08,357.529999,368.579987,357.399994,365.220001,365.220001,7449837

In [8]:
tesla_df.dtypes

Date         datetime64[us]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [9]:
tesla_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1791 entries, 0 to 1790
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       1791 non-null   datetime64[us]
 1   Open       1791 non-null   float64
 2   High       1791 non-null   float64
 3   Low        1791 non-null   float64
 4   Close      1791 non-null   float64
 5   Adj Close  1791 non-null   float64
 6   Volume     1791 non-null   int64
dtypes: datetime64[us](1), float64(5), int64(1)
memory usage: 98.1 KB

In [10]:
tesla_df.dtypes

Date         datetime64[us]
Open                float64
High                float64
Low                 float64
Close               float64
Adj Close           float64
Volume                int64
dtype: object

In [11]:
tesla_df['Day'] = tesla_df['Date'].dt.day # .dt.day is used to get the day from the date column

tesla_df['Month'] = tesla_df['Date'].dt.month # .dt.month is used to get the month from the date column

tesla_df['Year'] = tesla_df['Date'].dt.year # .dt.year is used to get the year from the date column



tesla_df.head(10)

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010
6,2010-07-08,16.139999,17.520000,15.570000,17.459999,17.459999,7711400,8,7,2010
7,2010-07-09,17.580000,17.900000,16.549999,17.400000,17.400000,4050600,9,7,2010
8,2010-07-12,17.950001,18.070000,17.000000,17.049999,17.049999,2202500,12,7,2010
9,2010-07-13,17.389999,18.639999,16.900000,18.139999,18.139999,2680100,13,7,2010

In [12]:
print(tesla_df['Date'].max())
print(tesla_df['Date'].min())

2017-08-08 00:00:00
2010-06-29 00:00:00

In [13]:
monthly_sales = tesla_df.groupby(['Year', 'Month'])['Volume'].sum().reset_index()
monthly_sales

    Year  Month     Volume
0   2010      6   35953400
1   2010      7   64575800
2   2010      8   15038200
3   2010      9   18045900
4   2010     10    6547800
..   ...    ...        ...
82  2017      4  116950600
83  2017      5  148007800
84  2017      6  185930900
85  2017      7  181640000
86  2017      8   57854737

[87 rows x 3 columns]

In [14]:
# Filter data between two dates
filtered_df_twoDate = tesla_df.loc[(tesla_df['Date'] >= '2010-02-01') & (tesla_df['Date'] < '2010-12-01')]
# Display
filtered_df_twoDate

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010
...,...,...,...,...,...,...,...,...,...,...
103,2010-11-23,33.290001,35.680000,32.189999,34.570000,34.570000,1577800,23,11,2010
104,2010-11-24,35.270000,35.970001,34.330002,35.470001,35.470001,1425000,24,11,2010
105,2010-11-26,35.599998,36.000000,34.750000,35.320000,35.320000,350600,26,11,2010
106,2010-11-29,35.410000,35.950001,33.330002,34.330002,34.330002,1145600,29,11,2010
107,2010-11-30,33.740002,35.330002,33.410000,35.330002,35.330002,2222600,30,11,2010

In [15]:
filtered_df_twoDate = tesla_df.query("Date >= '2010-02-01' and Date < '2010-12-01'")
filtered_df_twoDate

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year
0,2010-06-29,19.000000,25.000000,17.540001,23.889999,23.889999,18766300,29,6,2010
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010
2,2010-07-01,25.000000,25.920000,20.270000,21.959999,21.959999,8218800,1,7,2010
3,2010-07-02,23.000000,23.100000,18.709999,19.200001,19.200001,5139800,2,7,2010
4,2010-07-06,20.000000,20.000000,15.830000,16.110001,16.110001,6866900,6,7,2010
...,...,...,...,...,...,...,...,...,...,...
103,2010-11-23,33.290001,35.680000,32.189999,34.570000,34.570000,1577800,23,11,2010
104,2010-11-24,35.270000,35.970001,34.330002,35.470001,35.470001,1425000,24,11,2010
105,2010-11-26,35.599998,36.000000,34.750000,35.320000,35.320000,350600,26,11,2010
106,2010-11-29,35.410000,35.950001,33.330002,34.330002,34.330002,1145600,29,11,2010
107,2010-11-30,33.740002,35.330002,33.410000,35.330002,35.330002,2222600,30,11,2010

In [16]:
filtered_df_week = tesla_df.loc[tesla_df['Date'].dt.weekday == 2]
filtered_df_week

,Date,Open,High,Low,Close,Adj Close,Volume,Day,Month,Year
1,2010-06-30,25.790001,30.420000,23.299999,23.830000,23.830000,17187100,30,6,2010
5,2010-07-07,16.400000,16.629999,14.980000,15.800000,15.800000,6921700,7,7,2010
10,2010-07-14,17.940001,20.150000,17.760000,19.840000,19.840000,4195200,14,7,2010
15,2010-07-21,20.660000,20.900000,19.500000,20.219999,20.219999,1252500,21,7,2010
20,2010-07-28,20.549999,20.900000,20.510000,20.719999,20.719999,467200,28,7,2010
...,...,...,...,...,...,...,...,...,...,...
1766,2017-07-05,347.200012,347.239990,326.329987,327.089996,327.089996,17046700,5,7,2017
1771,2017-07-12,330.399994,333.100006,324.500000,329.519989,329.519989,10346100,12,7,2017
1776,2017-07-19,328.230011,331.649994,323.220001,325.260010,325.260010,6357000,19,7,2017
1781,2017-07-26,340.359985,345.500000,338.119995,343.850006,343.850006,4820800,26,7,2017
1786,2017-08-02,318.940002,327.119995,311.220001,325.890015,325.890015,13091500,2,8,2017