Advanced Pandas

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# handling multiple dataframes
- 'df.merge()' - similar to join in sql - columns or keys/columns; make the data set wider, add column
- 'df.join()' - similar to a join in sql - combinnes dataframes on an index, make the data set wider, add columns
- 'df.concat' - similar to a union in sql - add rows, stacking DF on top of each other, add rows and make the dataset longer
- 'df.append()' - deprecated, don't use, use concat instead

# use .concat

In [3]:
df1 = pd.read_csv('data/RealEstate1.csv')
df2 = pd.read_csv('data/RealEstate2.csv')
df3 = pd.read_csv('data/RealEstate3.csv')

In [6]:
real_estate_df = pd.concat([df1, df2, df3], ignore_index=True)
print(real_estate_df)

    ID     MLS            Location    Price  Bedrooms  Bathrooms  Size  \
0    1  143178  Santa Maria-Orcutt   375000         4          2  1963
1    2  143217  Santa Maria-Orcutt   330000         3          3  1900
2    3  143252  Santa Maria-Orcutt   199000         3          3  1450
3    4  143255  Santa Maria-Orcutt   165000         2          2  1000
4    5  143436           Templeton  1399000         4          3  6500
5    6  143507  Santa Maria-Orcutt   255000         3          2  1218
6    7  143524             Cambria   325000         2          2   893
7    8  143534           Morro Bay   789000         3          3  2100
8    9  143540              Nipomo   498000         4          3  2341
9   10  143884              Nipomo   430000         4          2  2168
10  11  143946         Paso Robles   539900         4          3  3032
11  12  144204         Pismo Beach   499000         3          2  1293
12  12  144238            Los Osos   275000         3          2  1200

    Price SQ Ft       Status
0        191.03   Short Sale
1        173.68   Short Sale
2        137.24   Short Sale
3        165.00   Short Sale
4        215.23  Foreclosure
5        209.36   Short Sale
6        363.94   Short Sale
7        375.71  Foreclosure
8        212.73   Short Sale
9        198.34   Short Sale
10       178.07   Short Sale
11       385.92   Short Sale
12       229.17   Short Sale

In [7]:
# create a subset of records that have more than 3 bedrooms
subset = real_estate_df[ real_estate_df['Bedrooms'] > 3 ]
print(subset)

    ID     MLS            Location    Price  Bedrooms  Bathrooms  Size  \
0    1  143178  Santa Maria-Orcutt   375000         4          2  1963
4    5  143436           Templeton  1399000         4          3  6500
8    9  143540              Nipomo   498000         4          3  2341
9   10  143884              Nipomo   430000         4          2  2168
10  11  143946         Paso Robles   539900         4          3  3032

    Price SQ Ft       Status
0        191.03   Short Sale
4        215.23  Foreclosure
8        212.73   Short Sale
9        198.34   Short Sale
10       178.07   Short Sale

In [8]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },

)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },

)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },

)

frames = [df1, df2, df3]
df = pd.concat(frames, ignore_index=True)

In [9]:
df

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [10]:
df_with_heirarchy = pd.concat(frames, keys=[ 'x', 'y', 'z'])
df_with_heirarchy

       A    B    C    D
x 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [12]:
# Access the 'y' group from the MultiIndex DataFrame
result = df_with_heirarchy.loc['y']
result

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [13]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [ ]:
# Merge the two DataFrames on the shared "Courses" column
merged_df = left_df.merge(
    right_df,
    on="Courses",
    how="inner",
    suffixes=("_left", "_right")
)
print("Inner merge:")
print(merged_df)

# Left join to keep all rows from left_df
left_join_df = left_df.merge(
    right_df,
    on="Courses",
    how="left",
    suffixes=("_left", "_right")
)
print("\nLeft join:")
print(left_join_df)

In [14]:
print('DF1: ', left_df)
print('DF2: ', right_df)

DF1:     Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Python  30000   60days
3   pandas  24000   55days
4     Java  40000   50days
DF2:      Courses    Fee Percentage
0      Java  20000        10%
1   PySpark  25000        20%
2    Python  30000        25%
3    pandas  24000        20%
4  Hyperion  40000        10%
5      html   4000        50%

In [16]:
# pands function merge
merge_df = pd.merge(left_df, right_df, on='Courses')
print(merge_df)

   Courses  Fee_x Duration  Fee_y Percentage
0  PySpark  25000   40days  25000        20%
1   Python  30000   60days  30000        25%
2   pandas  24000   55days  24000        20%
3     Java  40000   50days  20000        10%

In [17]:
merge_df = pd.merge(left_df, right_df)
print(merge_df)

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [19]:
merge_df = pd.merge(left_df, right_df, on=['Courses', 'Fee'])
print(merge_df)

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [ ]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Price' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Class': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [ ]:
result = pd.merge(left_df, right_df, left_on=['Courses', 'Price'], right_on['Class', 'Fee'])
result

In [24]:
# Create a DataFrame with sales transactions
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'ProductID': [101, 102, 103, 101, 105],
    'StoreID': [1, 2, 1, 3, 2],
    'Quantity': [5, 3, 2, 4, 1],
    'Amount': [500.00, 300.00, 200.00, 400.00, 150.00]
}

df_sales = pd.DataFrame(sales_data)

# Create a DataFrame with product details
products_data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Headphones', 'Smartphone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
}

df_products = pd.DataFrame(products_data)

In [ ]:
merge_df = pd.merge(df_sales, df_products, how='left', on='ProductID')
merge_df

In [38]:
left = pd.DataFrame({"A": [1, 2], "B": [1, 2]})

right = pd.DataFrame({"A": [4, 5, 6], "B": [2, 2, 2]})

In [39]:
pd.merge(left, right, on='B', how='inner')

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [ ]:
# pd.merge(left, right, on='B', how='inner', validate='one_to_one')
# merge method, you can use 'A' or 'B'
left = left.merge(right, on='B')

In [41]:
left = left.merge(right, on='B')
left

   A_x  B  A_y  A
0    2  2    4  4
1    2  2    4  5
2    2  2    4  6
3    2  2    5  4
4    2  2    5  5
5    2  2    5  6
6    2  2    6  4
7    2  2    6  5
8    2  2    6  6

## JOIN

In [1]:
technologies = {
    'Courses':["Spark","PySpark","Python","pandas"],
    'Fee' :[20000,25000,22000,30000],
    'Duration':['30days','40days','35days','50days'],
              }
index_labels=['r1','r2','r3','r4']
df1 = pd.DataFrame(technologies,index=index_labels)

print("First DataFrame:\n", df1)

technologies2 = {
    'Courses':["Spark","Java","Python","Go"],
    'Discount':[2000,2300,1200,2000]
              }
index_labels2=['r1','r6','r3','r5']
df2 = pd.DataFrame(technologies2,index=index_labels2)

print("Second DataFRame:\n", df2)

NameError: name 'pd' is not defined

In [ ]:
# df.join(other, lsuffix="_called", rsuffix="_other")
# by default it joins using what (=index values)
df1.join(df2, lsuffix='_left', rsuffix='_right')

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark    2000.0
r2      PySpark  25000   40days           NaN       NaN
r3       Python  22000   35days        Python    1200.0
r4       pandas  30000   50days           NaN       NaN

In [ ]:
df1.join(df2, lsuffix='_left', rsuffix='_right', how='right')

   Courses_left      Fee Duration Courses_right  Discount
r1        Spark  20000.0   30days         Spark      2000
r6          NaN      NaN      NaN          Java      2300
r3       Python  22000.0   35days        Python      1200
r5          NaN      NaN      NaN            Go      2000

In [ ]:
df1.join(df2, lsuffix='_left', rsuffix='_right', how='inner')

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark      2000
r3       Python  22000   35days        Python      1200

In [ ]:
df1.set_index('Courses').join(df2.set_index('Courses'), lsuffix='_left', rsuffix='_right')

           Fee Duration  Discount
Courses
Spark    20000   30days    2000.0
PySpark  25000   40days       NaN
Python   22000   35days    1200.0
pandas   30000   50days       NaN

Aggregate function Practice