Advanced Pandas

In [1]:
import pandas as pd
import numpy as np

In [ ]:
# handling multiple dataframes
- 'df.merge()' - similar to join in sql - columns or keys/columns; make the data set wider, add column
- 'df.join()' - similar to a join in sql - combinnes dataframes on an index, make the data set wider, add columns
- 'df.concat' - similar to a union in sql - add rows, stacking DF on top of each other, add rows and make the dataset longer
- 'df.append()' - deprecated, don't use, use concat instead

# use .concat

In [3]:
df1 = pd.read_csv('data/RealEstate1.csv')
df2 = pd.read_csv('data/RealEstate2.csv')
df3 = pd.read_csv('data/RealEstate3.csv')

In [6]:
real_estate_df = pd.concat([df1, df2, df3], ignore_index=True)
print(real_estate_df)

    ID     MLS            Location    Price  Bedrooms  Bathrooms  Size  \
0    1  143178  Santa Maria-Orcutt   375000         4          2  1963
1    2  143217  Santa Maria-Orcutt   330000         3          3  1900
2    3  143252  Santa Maria-Orcutt   199000         3          3  1450
3    4  143255  Santa Maria-Orcutt   165000         2          2  1000
4    5  143436           Templeton  1399000         4          3  6500
5    6  143507  Santa Maria-Orcutt   255000         3          2  1218
6    7  143524             Cambria   325000         2          2   893
7    8  143534           Morro Bay   789000         3          3  2100
8    9  143540              Nipomo   498000         4          3  2341
9   10  143884              Nipomo   430000         4          2  2168
10  11  143946         Paso Robles   539900         4          3  3032
11  12  144204         Pismo Beach   499000         3          2  1293
12  12  144238            Los Osos   275000         3          2  1200

    Price SQ Ft       Status
0        191.03   Short Sale
1        173.68   Short Sale
2        137.24   Short Sale
3        165.00   Short Sale
4        215.23  Foreclosure
5        209.36   Short Sale
6        363.94   Short Sale
7        375.71  Foreclosure
8        212.73   Short Sale
9        198.34   Short Sale
10       178.07   Short Sale
11       385.92   Short Sale
12       229.17   Short Sale

In [7]:
# create a subset of records that have more than 3 bedrooms
subset = real_estate_df[ real_estate_df['Bedrooms'] > 3 ]
print(subset)

    ID     MLS            Location    Price  Bedrooms  Bathrooms  Size  \
0    1  143178  Santa Maria-Orcutt   375000         4          2  1963
4    5  143436           Templeton  1399000         4          3  6500
8    9  143540              Nipomo   498000         4          3  2341
9   10  143884              Nipomo   430000         4          2  2168
10  11  143946         Paso Robles   539900         4          3  3032

    Price SQ Ft       Status
0        191.03   Short Sale
4        215.23  Foreclosure
8        212.73   Short Sale
9        198.34   Short Sale
10       178.07   Short Sale

In [8]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],
    },

)


df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],
    },

)


df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"],
    },

)

frames = [df1, df2, df3]
df = pd.concat(frames, ignore_index=True)

In [9]:
df

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [10]:
df_with_heirarchy = pd.concat(frames, keys=[ 'x', 'y', 'z'])
df_with_heirarchy

       A    B    C    D
x 0   A0   B0   C0   D0
  1   A1   B1   C1   D1
  2   A2   B2   C2   D2
  3   A3   B3   C3   D3
y 0   A4   B4   C4   D4
  1   A5   B5   C5   D5
  2   A6   B6   C6   D6
  3   A7   B7   C7   D7
z 0   A8   B8   C8   D8
  1   A9   B9   C9   D9
  2  A10  B10  C10  D10
  3  A11  B11  C11  D11

In [12]:
# Access the 'y' group from the MultiIndex DataFrame
result = df_with_heirarchy.loc['y']
result

    A   B   C   D
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [13]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Fee' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Courses': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [ ]:
# Merge the two DataFrames on the shared "Courses" column
merged_df = left_df.merge(
    right_df,
    on="Courses",
    how="inner",
    suffixes=("_left", "_right")
)
print("Inner merge:")
print(merged_df)

# Left join to keep all rows from left_df
left_join_df = left_df.merge(
    right_df,
    on="Courses",
    how="left",
    suffixes=("_left", "_right")
)
print("\nLeft join:")
print(left_join_df)

In [14]:
print('DF1: ', left_df)
print('DF2: ', right_df)

DF1:     Courses    Fee Duration
0    Spark  20000    30day
1  PySpark  25000   40days
2   Python  30000   60days
3   pandas  24000   55days
4     Java  40000   50days
DF2:      Courses    Fee Percentage
0      Java  20000        10%
1   PySpark  25000        20%
2    Python  30000        25%
3    pandas  24000        20%
4  Hyperion  40000        10%
5      html   4000        50%

In [16]:
# pands function merge
merge_df = pd.merge(left_df, right_df, on='Courses')
print(merge_df)

   Courses  Fee_x Duration  Fee_y Percentage
0  PySpark  25000   40days  25000        20%
1   Python  30000   60days  30000        25%
2   pandas  24000   55days  24000        20%
3     Java  40000   50days  20000        10%

In [17]:
merge_df = pd.merge(left_df, right_df)
print(merge_df)

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [19]:
merge_df = pd.merge(left_df, right_df, on=['Courses', 'Fee'])
print(merge_df)

   Courses    Fee Duration Percentage
0  PySpark  25000   40days        20%
1   Python  30000   60days        25%
2   pandas  24000   55days        20%

In [ ]:
left_df = pd.DataFrame({'Courses': ["Spark","PySpark","Python","pandas","Java"],
                    'Price' : [20000,25000,30000,24000,40000],
                    'Duration':['30day','40days','60days','55days','50days']})

right_df = pd.DataFrame({'Class': ["Java","PySpark","Python","pandas","Hyperion","html"],
                    'Fee': [20000,25000,30000,24000,40000,4000],
                    'Percentage':['10%','20%','25%','20%','10%','50%']})

In [ ]:
result = pd.merge(left_df, right_df, left_on=['Courses', 'Price'], right_on['Class', 'Fee'])
result

In [24]:
# Create a DataFrame with sales transactions
sales_data = {
    'TransactionID': [1, 2, 3, 4, 5],
    'ProductID': [101, 102, 103, 101, 105],
    'StoreID': [1, 2, 1, 3, 2],
    'Quantity': [5, 3, 2, 4, 1],
    'Amount': [500.00, 300.00, 200.00, 400.00, 150.00]
}

df_sales = pd.DataFrame(sales_data)

# Create a DataFrame with product details
products_data = {
    'ProductID': [101, 102, 103, 104, 105],
    'ProductName': ['Laptop', 'Headphones', 'Smartphone', 'Tablet', 'Monitor'],
    'Category': ['Electronics', 'Electronics', 'Electronics', 'Electronics', 'Electronics']
}

df_products = pd.DataFrame(products_data)

In [ ]:
merge_df = pd.merge(df_sales, df_products, how='left', on='ProductID')
merge_df

In [38]:
left = pd.DataFrame({"A": [1, 2], "B": [1, 2]})

right = pd.DataFrame({"A": [4, 5, 6], "B": [2, 2, 2]})

In [39]:
pd.merge(left, right, on='B', how='inner')

   A_x  B  A_y
0    2  2    4
1    2  2    5
2    2  2    6

In [ ]:
# pd.merge(left, right, on='B', how='inner', validate='one_to_one')
# merge method, you can use 'A' or 'B'
left = left.merge(right, on='B')

In [41]:
left = left.merge(right, on='B')
left

   A_x  B  A_y  A
0    2  2    4  4
1    2  2    4  5
2    2  2    4  6
3    2  2    5  4
4    2  2    5  5
5    2  2    5  6
6    2  2    6  4
7    2  2    6  5
8    2  2    6  6

## JOIN

In [1]:
technologies = {
    'Courses':["Spark","PySpark","Python","pandas"],
    'Fee' :[20000,25000,22000,30000],
    'Duration':['30days','40days','35days','50days'],
              }
index_labels=['r1','r2','r3','r4']
df1 = pd.DataFrame(technologies,index=index_labels)

print("First DataFrame:\n", df1)

technologies2 = {
    'Courses':["Spark","Java","Python","Go"],
    'Discount':[2000,2300,1200,2000]
              }
index_labels2=['r1','r6','r3','r5']
df2 = pd.DataFrame(technologies2,index=index_labels2)

print("Second DataFRame:\n", df2)

NameError: name 'pd' is not defined

In [ ]:
# df.join(other, lsuffix="_called", rsuffix="_other")
# by default it joins using what (=index values)
df1.join(df2, lsuffix='_left', rsuffix='_right')

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark    2000.0
r2      PySpark  25000   40days           NaN       NaN
r3       Python  22000   35days        Python    1200.0
r4       pandas  30000   50days           NaN       NaN

In [ ]:
df1.join(df2, lsuffix='_left', rsuffix='_right', how='right')

   Courses_left      Fee Duration Courses_right  Discount
r1        Spark  20000.0   30days         Spark      2000
r6          NaN      NaN      NaN          Java      2300
r3       Python  22000.0   35days        Python      1200
r5          NaN      NaN      NaN            Go      2000

In [ ]:
df1.join(df2, lsuffix='_left', rsuffix='_right', how='inner')

   Courses_left    Fee Duration Courses_right  Discount
r1        Spark  20000   30days         Spark      2000
r3       Python  22000   35days        Python      1200

In [ ]:
df1.set_index('Courses').join(df2.set_index('Courses'), lsuffix='_left', rsuffix='_right')

           Fee Duration  Discount
Courses
Spark    20000   30days    2000.0
PySpark  25000   40days       NaN
Python   22000   35days    1200.0
pandas   30000   50days       NaN

Aggregate function Practice

In [3]:
import pandas as pd
import numpy as np

In [5]:
zoo = pd.read_csv("data/zoo.csv")
zoo.head()

     animal  uniq_id  water_need
0  elephant     1001         500
1  elephant     1002         600
2  elephant     1003         550
3     tiger     1004         300
4     tiger     1005         320

In [6]:
zoo.count()

animal        22
uniq_id       22
water_need    22
dtype: int64

In [8]:
zoo[['animal']].count()

animal    22
dtype: int64

In [9]:
zoo.animal.count()

np.int64(22)

In [10]:
# total amount of water needed
zoo.water_need.sum()

np.int64(7650)

In [11]:
zoo[['water_need']].sum()

water_need    7650
dtype: int64

In [12]:
zoo.sum()

animal        elephantelephantelephanttigertigertigertigerti...
uniq_id                                                   22253
water_need                                                 7650
dtype: object

In [13]:
zoo['water_need'].agg(['min', 'max', 'mean', 'median'])

min        80.000000
max       600.000000
mean      347.727273
median    325.000000
Name: water_need, dtype: float64

In [15]:
min = zoo[['water_need']].min()
max = zoo[['water_need']].max()
mean = zoo[['water_need']].mean()
median = zoo[['water_need']].median()
print(min, max, mean, median)

water_need    80
dtype: int64 water_need    600
dtype: int64 water_need    347.727273
dtype: float64 water_need    325.0
dtype: float64

In [16]:
result = zoo[['water_need']].agg(['min', 'max', 'mean', 'median'])
result

        water_need
min      80.000000
max     600.000000
mean    347.727273
median  325.000000

In [17]:
# calculate the mean water needed for each animal group

In [21]:
# more standard with double bracket
zoo.groupby('animal')[['water_need']].mean()

          water_need
animal
elephant  550.000000
kangaroo  416.666667
lion      477.500000
tiger     310.000000
zebra     184.285714

In [19]:
group_water_need = zoo.groupby('animal')['water_need'].mean()
print(group_water_need)

animal
elephant    550.000000
kangaroo    416.666667
lion        477.500000
tiger       310.000000
zebra       184.285714
Name: water_need, dtype: float64

In [20]:
# also we can use this
zoo.groupby('animal').water_need.mean()

animal
elephant    550.000000
kangaroo    416.666667
lion        477.500000
tiger       310.000000
zebra       184.285714
Name: water_need, dtype: float64

In [22]:
df = pd.read_csv('data/student_scores.csv')
print(df.head())

      id first_name last_name       birth gender class     Subject  score
0  10001       John       Doe  2000-01-01      M     A    Calculus     63
1  10001       John       Doe  2000-01-01      M     A    Geometry     65
2  10001       John       Doe  2000-01-01      M     A  Statistics     63
3  10002       Jane     Smith  2000-01-02      F     B    Calculus     63
4  10002       Jane     Smith  2000-01-02      F     B    Geometry     64

In [24]:

# check for data integrity: shape, descriptive stats, date types

In [25]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 8 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id          27 non-null     int64
 1   first_name  27 non-null     str
 2   last_name   27 non-null     str
 3   birth       27 non-null     str
 4   gender      27 non-null     str
 5   class       27 non-null     str
 6   Subject     27 non-null     str
 7   score       27 non-null     int64
dtypes: int64(2), str(6)
memory usage: 1.8 KB
None

In [26]:
item_group = df.groupby('first_name')
print(item_group.groups)

{'Bob': [24, 25, 26], 'Frank': [9, 10, 11], 'Fred': [21, 22, 23], 'Jane': [3, 4, 5], 'Jennifer': [15, 16, 17], 'Jessica': [18, 19, 20], 'John': [0, 1, 2], 'Mike': [12, 13, 14], 'Sarah': [6, 7, 8]}

In [27]:
item_group = df.groupby(['first_name', 'last_name'])
print(item_group.groups)

{('Bob', 'Lopez'): RangeIndex(start=24, stop=27, step=1), ('Frank', 'Brown'): RangeIndex(start=9, stop=12, step=1), ('Fred', 'Clark'): RangeIndex(start=21, stop=24, step=1), ('Jane', 'Smith'): RangeIndex(start=3, stop=6, step=1), ('Jennifer', 'Wilson'): RangeIndex(start=15, stop=18, step=1), ('Jessica', 'Garcia'): RangeIndex(start=18, stop=21, step=1), ('John', 'Doe'): RangeIndex(start=0, stop=3, step=1), ('Mike', 'Davis'): RangeIndex(start=12, stop=15, step=1), ('Sarah', 'Thomas'): RangeIndex(start=6, stop=9, step=1)}

In [28]:
print(df.duplicated().sum())

0

In [30]:
for group, val in item_group:
    print(group)
    print(val, '\n')

('Bob', 'Lopez')
       id first_name last_name       birth gender class     Subject  score
24  10009        Bob     Lopez  2000-01-09      F     B    Calculus     91
25  10009        Bob     Lopez  2000-01-09      F     B    Geometry     81
26  10009        Bob     Lopez  2000-01-09      F     B  Statistics     75

('Frank', 'Brown')
       id first_name last_name       birth gender class     Subject  score
9   10004      Frank     Brown  2000-01-04      M     A    Calculus     88
10  10004      Frank     Brown  2000-01-04      M     A    Geometry     73
11  10004      Frank     Brown  2000-01-04      M     A  Statistics     86

('Fred', 'Clark')
       id first_name last_name       birth gender class     Subject  score
21  10008       Fred     Clark  2000-01-08      F     C    Calculus     66
22  10008       Fred     Clark  2000-01-08      F     C    Geometry     71
23  10008       Fred     Clark  2000-01-08      F     C  Statistics     94

('Jane', 'Smith')
      id first_name last_name       birth gender class     Subject  score
3  10002       Jane     Smith  2000-01-02      F     B    Calculus     63
4  10002       Jane     Smith  2000-01-02      F     B    Geometry     64
5  10002       Jane     Smith  2000-01-02      F     B  Statistics     94

('Jennifer', 'Wilson')
       id first_name last_name       birth gender class     Subject  score
15  10006   Jennifer    Wilson  2000-01-06      M     C    Calculus     90
16  10006   Jennifer    Wilson  2000-01-06      M     C    Geometry     78
17  10006   Jennifer    Wilson  2000-01-06      M     C  Statistics     68

('Jessica', 'Garcia')
       id first_name last_name       birth gender class     Subject  score
18  10007    Jessica    Garcia  2000-01-07      F     B    Calculus     70
19  10007    Jessica    Garcia  2000-01-07      F     B    Geometry     83
20  10007    Jessica    Garcia  2000-01-07      F     B  Statistics     80

('John', 'Doe')
      id first_name last_name       birth gender class     Subject  score
0  10001       John       Doe  2000-01-01      M     A    Calculus     63
1  10001       John       Doe  2000-01-01      M     A    Geometry     65
2  10001       John       Doe  2000-01-01      M     A  Statistics     63

('Mike', 'Davis')
       id first_name last_name       birth gender class     Subject  score
12  10005       Mike     Davis  2000-01-05      F     C    Calculus     94
13  10005       Mike     Davis  2000-01-05      F     C    Geometry     78
14  10005       Mike     Davis  2000-01-05      F     C  Statistics     90

('Sarah', 'Thomas')
      id first_name last_name       birth gender class     Subject  score
6  10003      Sarah    Thomas  2000-01-03      M     B    Calculus     96
7  10003      Sarah    Thomas  2000-01-03      M     B    Geometry     73
8  10003      Sarah    Thomas  2000-01-03      M     B  Statistics     61

In [31]:
subjects = df.groupby('Subject')

In [32]:
print(subjects.get_group('Calculus'))

       id first_name last_name       birth gender class   Subject  score
0   10001       John       Doe  2000-01-01      M     A  Calculus     63
3   10002       Jane     Smith  2000-01-02      F     B  Calculus     63
6   10003      Sarah    Thomas  2000-01-03      M     B  Calculus     96
9   10004      Frank     Brown  2000-01-04      M     A  Calculus     88
12  10005       Mike     Davis  2000-01-05      F     C  Calculus     94
15  10006   Jennifer    Wilson  2000-01-06      M     C  Calculus     90
18  10007    Jessica    Garcia  2000-01-07      F     B  Calculus     70
21  10008       Fred     Clark  2000-01-08      F     C  Calculus     66
24  10009        Bob     Lopez  2000-01-09      F     B  Calculus     91

In [33]:
print(subjects.get_group('Calculus')[['score']].mean())

score    80.111111
dtype: float64

In [ ]:
# create a table with the average grades for each subject

In [34]:
df.groupby('Subject', as_index=False)['score'].mean()

      Subject      score
0    Calculus  80.111111
1    Geometry  74.000000
2  Statistics  79.000000

In [35]:
print(df.groupby('Subject')[['score']].mean())

                score
Subject
Calculus    80.111111
Geometry    74.000000
Statistics  79.000000

In [37]:
df.groupby('Subject')[['score']].agg(['mean', 'min', 'max'])

                score
                 mean min max
Subject
Calculus    80.111111  63  96
Geometry    74.000000  64  83
Statistics  79.000000  61  94

In [38]:
# group by first and last name and find their mean score
df.groupby(['first_name', 'last_name'])[['score']].mean()

                          score
first_name last_name
Bob        Lopez      82.333333
Frank      Brown      82.333333
Fred       Clark      77.000000
Jane       Smith      73.666667
Jennifer   Wilson     78.666667
Jessica    Garcia     77.666667
John       Doe        63.666667
Mike       Davis      87.333333
Sarah      Thomas     76.666667

In [39]:
df.groupby(['first_name', 'last_name'])[['score']].mean().sort_values('score')

                          score
first_name last_name
John       Doe        63.666667
Jane       Smith      73.666667
Sarah      Thomas     76.666667
Fred       Clark      77.000000
Jessica    Garcia     77.666667
Jennifer   Wilson     78.666667
Bob        Lopez      82.333333
Frank      Brown      82.333333
Mike       Davis      87.333333

In [ ]:
# count the number of students, find the student with the highest score, find the student with lowest score

In [40]:
# Count unique students and compare their average scores across subjects
student_scores = (
    df.groupby(['id', 'first_name', 'last_name'], as_index=False)['score']
      .mean()
      .rename(columns={'score': 'average_score'})
)

print("Number of students:", df['id'].nunique())
print("\nStudent with the highest average score:")
print(student_scores.loc[student_scores['average_score'].idxmax()])

print("\nStudent with the lowest average score:")
print(student_scores.loc[student_scores['average_score'].idxmin()])

Number of students: 9

Student with the highest average score:
id                   10005
first_name            Mike
last_name            Davis
average_score    87.333333
Name: 4, dtype: object

Student with the lowest average score:
id                   10001
first_name            John
last_name              Doe
average_score    63.666667
Name: 0, dtype: object

In [42]:
df.groupby(['id', 'first_name', 'last_name'])[['score']].mean()

                                score
id    first_name last_name
10001 John       Doe        63.666667
10002 Jane       Smith      73.666667
10003 Sarah      Thomas     76.666667
10004 Frank      Brown      82.333333
10005 Mike       Davis      87.333333
10006 Jennifer   Wilson     78.666667
10007 Jessica    Garcia     77.666667
10008 Fred       Clark      77.000000
10009 Bob        Lopez      82.333333

In [43]:
df.groupby(['id', 'first_name', 'last_name'])[['score']].max()

                            score
id    first_name last_name
10001 John       Doe           65
10002 Jane       Smith         94
10003 Sarah      Thomas        96
10004 Frank      Brown         88
10005 Mike       Davis         94
10006 Jennifer   Wilson        90
10007 Jessica    Garcia        83
10008 Fred       Clark         94
10009 Bob        Lopez         91

In [46]:
df.groupby(['id', 'first_name', 'last_name']).min()[['score']]

                            score
id    first_name last_name
10001 John       Doe           63
10002 Jane       Smith         63
10003 Sarah      Thomas        61
10004 Frank      Brown         73
10005 Mike       Davis         78
10006 Jennifer   Wilson        68
10007 Jessica    Garcia        70
10008 Fred       Clark         66
10009 Bob        Lopez         75

In [48]:
# Expanded Sample Dataset (20 rows)
data = {
    'Department': [
        'Sales',       'Sales',        'Sales',        'Sales',        'Sales',        'Sales',        'Engineering',        'Engineering',        'Engineering',        'Engineering',
        'Engineering',        'HR',        'HR',        'HR',        'HR',        'Marketing',        'Marketing',        'Marketing',        'Marketing',        'Marketing',
    ],
    'Employee': [
        'Alice',        'Bob',        'Charlie',        'David',        'Eva',        'Frank',        'Grace',        'Hannah',        'Ian',        'Jack',
        'Karen',        'Liam',        'Mona',        'Nathan',        'Olivia',        'Paul',       'Quinn',        'Rachel',        'Sam',        'Tina',
        ],
    'Salary': [
        70000,        80000,        75000,        82000,        68000,        79000,        110000,        120000,        115000,        105000,        125000,        65000,
        60000,        62000,        67000,        72000,        78000,        85000,        69000,        74000,
        ],
        'Bonus': [        5000,        8000,        6000,        8500,        4500,        7500,        12000,        15000,        13000,        11000,        16000,
        4000,        3000,        3500,        4200,        5500,        7000,        9000,        5000,        6000,
    ],
    'Performance_Score': [        88,        92,        85,        90,        82,        89,        95,        98,        94,        91,        99,        78,        82,
        80,        84,        87,        91,        93,        83,        88,    ],
}

df = pd.DataFrame(data)
df.head(20)

     Department Employee  Salary  Bonus  Performance_Score
0         Sales    Alice   70000   5000                 88
1         Sales      Bob   80000   8000                 92
2         Sales  Charlie   75000   6000                 85
3         Sales    David   82000   8500                 90
4         Sales      Eva   68000   4500                 82
5         Sales    Frank   79000   7500                 89
6   Engineering    Grace  110000  12000                 95
7   Engineering   Hannah  120000  15000                 98
8   Engineering      Ian  115000  13000                 94
9   Engineering     Jack  105000  11000                 91
10  Engineering    Karen  125000  16000                 99
11           HR     Liam   65000   4000                 78
12           HR     Mona   60000   3000                 82
13           HR   Nathan   62000   3500                 80
14           HR   Olivia   67000   4200                 84
15    Marketing     Paul   72000   5500                 87
16    Marketing    Quinn   78000   7000                 91
17    Marketing   Rachel   85000   9000                 93
18    Marketing      Sam   69000   5000                 83
19    Marketing     Tina   74000   6000                 88

In [ ]:
# 1: Calculate total, average, max values for salary in one command

# 2: Calculate min, max and average accross Salary and Bonus columns

# 3: Calculate Specific metrics for each column
    # Salary - mean, median per department
    # Performance - highest per department
    # Bonus - total paid per departments

# 4: For each departments - average salary per department, highest performance score per department, total bonus paid per department

In [53]:
df[['Salary']].agg(['sum', 'mean', 'max'])

         Salary
sum   1661000.0
mean    83050.0
max    125000.0

In [50]:
df[['Salary', 'Bonus']].agg(['min', 'max', 'mean'])

        Salary    Bonus
min    60000.0   3000.0
max   125000.0  16000.0
mean   83050.0   7685.0

In [51]:
department_metrics = df.groupby('Department').agg(
    Salary_mean=('Salary', 'mean'),
    Salary_median=('Salary', 'median'),
    Highest_Performance=('Performance_Score', 'max'),
    Total_Bonus=('Bonus', 'sum')
)

department_metrics

               Salary_mean  Salary_median  Highest_Performance  Total_Bonus
Department
Engineering  115000.000000       115000.0                   99        67000
HR            63500.000000        63500.0                   84        14700
Marketing     75600.000000        74000.0                   93        32500
Sales         75666.666667        77000.0                   92        39500

In [55]:
df.groupby('Department').agg(
    Average_Salary=('Salary', 'mean'),
    Highest_Performance=('Performance_Score', 'max'),
    Total_Bonus=('Bonus', 'sum')
)

             Average_Salary  Highest_Performance  Total_Bonus
Department
Engineering   115000.000000                   99        67000
HR             63500.000000                   84        14700
Marketing      75600.000000                   93        32500
Sales          75666.666667                   92        39500