# Pandas Notes

In [2]:
import pandas as pd
import numpy as np

#### Pandas DataTypes
-   series (`s`) - single dimensional array. Single column.
    -   homogenous - 1 data type per series
-   dataframe (`df`) - two dimensional array (table). Collection of columns.

In [13]:
# declare series
ser = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))

# Give it a name attribute
ser.name = 'alphabet'

# .head(n) - shows top 5 records - n = number of records
print(ser.head())

# .tail(n) - shop the bottom 5 records - n = number of records
print(ser.tail())

0    a
1    b
2    c
3    d
4    e
Name: alphabet, dtype: str
21    v
22    w
23    x
24    y
25    z
Name: alphabet, dtype: str

In [17]:
# Declare a series from a dictionary
d = {
    'a': 0.0,
    'b': 1.0,
    'c': 2.0
}

# For a dictionary becoming a series, the keys become the indexes
float_series = pd.Series(d)

print(float_series)

a    0.0
b    1.0
c    2.0
dtype: float64

In [ ]:
# Index is specified, corresponding data will be pulled into the series
customer_index = pd.Series(d, index=['a', 'y', 'x'])

print(customer_index)

a    0.0
y    NaN
x    NaN
dtype: float64

In [25]:
calories = {
    'day1': 2200,
    'day2': 2500,
    'day3': 2700,
}


index = ['day1', 'day2']
# Create a series with the following(or similare dictionary). but only with days 1 and 2
calories_series = pd.Series(calories, index=index)

print(calories_series)

day1    2200
day2    2500
dtype: int64

In [27]:
# Series of scalar value. Each index will have the same value
scalar_series = pd.Series(5.0, index=['a', 'b', 'c', 'd', 'e'])

print(scalar_series)

a    5.0
b    5.0
c    5.0
d    5.0
e    5.0
dtype: float64

In [31]:
# Element-wise arithmatic with series
ser1 = pd.Series([2, 4, 6, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 9])

# Just like arrays, math with series, are element-wise
print(ser1 + ser2)
print(ser1 - ser2)
print(ser1 * ser2)
print(ser1 / ser2)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
# Compare series - element-wise
# Element-wise arithmatic with series
ser1 = pd.Series([2, 4, 6, 8, 10])
ser2 = pd.Series([1, 3, 5, 7, 9])

print(ser1 > ser2)

0    True
1    True
2    True
3    True
4    True
dtype: bool

### Working w/ DataFrames and JSON

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_json('data/cars.json')

In [5]:
cars_df = pd.read_json('data/cars.json')

# Look at the first and last 5 entries
print(cars_df.head())

                          Car   MPG  Cylinders  Displacement  Horsepower  \
0              Chevrolet Vega  25.0          4         140.0          75
1         Chevrolet Vega (sw)  22.0          4         140.0          72
2         Chevrolet Vega 2300  28.0          4         140.0          90
3             Chevrolet Woody  24.5          4          98.0          60
4  Chevrolete Chevelle Malibu  16.0          6         250.0         105

   Weight  Acceleration  Model Origin  quantity     city
0    2542          17.0     74     US       177       NJ
1    2408          19.0     71     US        91   DALLAS
2    2264          15.5     71     US        74    TEXAS
3    2164          22.1     76     US       241       OH
4    3897          18.5     75     US       206  NewYork

In [6]:
print(cars_df.tail())

                         Car   MPG  Cylinders  Displacement  Horsepower  \
156         Mercury Capri v6  21.0          6         155.0         107
157  Mercury Cougar Brougham  15.0          8         302.0         130
158    Mercury Grand Marquis  16.5          8         351.0         138
159           Mercury Lynx l  36.0          4          98.0          70
160          Mercury Marquis  11.0          8         429.0         208

     Weight  Acceleration  Model Origin  quantity     city
156    2472          14.0     73     US       158  NewYork
157    4295          14.9     77     US        27       NJ
158    3955          13.2     79     US       332   DALLAS
159    2125          17.3     82     US       425    TEXAS
160    4633          11.0     72     US       112       OH

In [7]:
# look at the descriptive statistics of quantitative columns
print(cars_df.describe())

              MPG   Cylinders  Displacement  Horsepower       Weight  \
count  161.000000  161.000000    161.000000  161.000000   161.000000
mean    23.801863    5.347826    185.232919  100.664596  2915.093168
std      8.810125    1.761607    105.394809   41.079640   890.293883
min      0.000000    3.000000     68.000000    0.000000  1613.000000
25%     17.000000    4.000000     98.000000   72.000000  2130.000000
50%     24.000000    4.000000    140.000000   88.000000  2625.000000
75%     31.000000    8.000000    302.000000  130.000000  3620.000000
max     46.600000    8.000000    440.000000  215.000000  4955.000000

       Acceleration       Model    quantity
count    161.000000  161.000000  161.000000
mean      15.509938   76.260870  224.875776
std        2.515780    3.818576  127.741084
min        8.000000   70.000000    5.000000
25%       14.000000   73.000000  112.000000
50%       15.500000   76.000000  227.000000
75%       17.100000   80.000000  337.000000
max       22.100000   82.000000  439.000000

In [8]:
# look at the shape of our data
rows = cars_df.shape[0]
columns = cars_df.shape[1]

print('Rows/Records: ', rows)
print('Columns: ', columns)

Rows/Records:  161
Columns:  11

In [9]:
rows, cols = cars_df.shape

print('Rows: ', rows)
print('Cols: ', cols)

Rows:  161
Cols:  11

In [10]:
# look at the dtypes
print(cars_df.dtypes)

Car                 str
MPG             float64
Cylinders         int64
Displacement    float64
Horsepower        int64
Weight            int64
Acceleration    float64
Model             int64
Origin              str
quantity          int64
city                str
dtype: object

In [11]:
# num of non-null values
print(cars_df.count())

Car             161
MPG             161
Cylinders       161
Displacement    161
Horsepower      161
Weight          161
Acceleration    161
Model           161
Origin          161
quantity        161
city            161
dtype: int64

In [12]:
# check for null or missing values
print(cars_df.isnull().sum())

Car             0
MPG             0
Cylinders       0
Displacement    0
Horsepower      0
Weight          0
Acceleration    0
Model           0
Origin          0
quantity        0
city            0
dtype: int64

In [13]:
print(cars_df.info())

<class 'pandas.DataFrame'>
RangeIndex: 161 entries, 0 to 160
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Car           161 non-null    str
 1   MPG           161 non-null    float64
 2   Cylinders     161 non-null    int64
 3   Displacement  161 non-null    float64
 4   Horsepower    161 non-null    int64
 5   Weight        161 non-null    int64
 6   Acceleration  161 non-null    float64
 7   Model         161 non-null    int64
 8   Origin        161 non-null    str
 9   quantity      161 non-null    int64
 10  city          161 non-null    str
dtypes: float64(3), int64(5), str(3)
memory usage: 14.0 KB
None

In [14]:
# Value Counts & Values
# print(cars_df['Car'].value_counts())
print(cars_df['city'].value_counts())

city
NewYork    36
NJ         35
DALLAS     33
TEXAS      30
OH         27
Name: count, dtype: int64

In [15]:
# Accessing Single values
# .at() label based
print(cars_df.at[143, 'Car'])

# .iat() index based
print(cars_df.iat[143, 0])

Mazda GLC 4
Mazda GLC 4

In [16]:
# Scenario: You need to loop over each column and perform an action on it.
print(cars_df.columns)

print(cars_df.columns[0])
print(cars_df.columns[1])

# Turn columns into iterable list
print(cars_df.columns.tolist())

Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin', 'quantity', 'city'],
      dtype='str')
Car
MPG
['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight', 'Acceleration', 'Model', 'Origin', 'quantity', 'city']

In [17]:
# Rows and Cols. 0 = rows, 1 = columns
print(cars_df.axes)

[RangeIndex(start=0, stop=161, step=1), Index(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight',
       'Acceleration', 'Model', 'Origin', 'quantity', 'city'],
      dtype='str')]

In [18]:
print(len(cars_df.axes[0]))

161

#### Handling CSV's with Pandas

In [19]:
# .read_csv(employee.csv)
df = pd.read_csv('data/employee.csv')
# read_csv into a df

# print the shape
rows, cols = df.shape
print(f'Rows: {rows}')
print(f'Cols: {cols}')

Rows: 15
Cols: 4

In [20]:
# look at the first 5 and last 5 records
print(df.head())

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [21]:
print(df.tail())

     Name   Age  Weight     Salary
10  Jenny   NaN   100.0    25632.0
11   Kenn   NaN   110.0    25632.0
12    Aly   NaN    90.0    25582.0
13   John  41.0    85.0  1528000.0
14    Ali  26.0    69.0        NaN

In [76]:
# look at data types
print(df.dtypes)

Name          str
Age       float64
Weight    float64
Salary    float64
dtype: object

In [22]:
print(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    14 non-null     str
 1   Age     12 non-null     float64
 2   Weight  14 non-null     float64
 3   Salary  12 non-null     float64
dtypes: float64(3), str(1)
memory usage: 612.0 bytes
None

In [23]:
#look at the descriptive statistics
print(df.describe())

             Age      Weight        Salary
count  12.000000   14.000000  1.200000e+01
mean   37.083333   84.285714  3.494070e+06
std     5.160309   12.368873  2.771220e+06
min    26.000000   69.000000  2.558200e+04
25%    33.750000   74.250000  1.152408e+06
50%    39.000000   85.000000  3.928000e+06
75%    41.250000   88.750000  4.753000e+06
max    42.000000  110.000000  8.428000e+06

In [24]:
# look at the null count
print(df.isnull().sum())

Name      1
Age       3
Weight    1
Salary    3
dtype: int64

In [25]:
# look at info and value counts
df['Name'].value_counts()

Name
James       1
Villers     1
VKole       1
Smith       1
Gayle       1
Adam        1
Rooter      1
Peterson    1
lynda       1
Jenny       1
Kenn        1
Aly         1
John        1
Ali         1
Name: count, dtype: int64

In [26]:
print(list(df.columns))

['Name', 'Age', 'Weight', 'Salary']

In [27]:
# Skip header, dont want header, you want to put your own column names, 'header=None, skiprows=1'
df = pd.read_csv('data/employee.csv', header=None, skiprows=1)

print(df)

           0     1      2          3
0      James  36.0   75.0  5428000.0
1    Villers  38.0   74.0  3428000.0
2      VKole  31.0   70.0  8428000.0
3      Smith  34.0   80.0  4428000.0
4      Gayle  40.0  100.0  4528000.0
5       Adam  40.0    NaN  4528000.0
6     Rooter  33.0   72.0  7028000.0
7   Peterson  42.0   85.0  2528000.0
8      lynda  42.0   85.0        NaN
9        NaN  42.0   85.0        NaN
10     Jenny   NaN  100.0    25632.0
11      Kenn   NaN  110.0    25632.0
12       Aly   NaN   90.0    25582.0
13      John  41.0   85.0  1528000.0
14       Ali  26.0   69.0        NaN

In [28]:
# If selecting only certain columns for DA. Do it at import. The less data in memory the faster the program runs
df = pd.read_csv('data/employee.csv', usecols=['Name', 'Salary'])

print(df)

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

In [29]:
# Index based
df = pd.read_csv('data/employee.csv', usecols=[0, 3])

print(df)

        Name     Salary
0      James  5428000.0
1    Villers  3428000.0
2      VKole  8428000.0
3      Smith  4428000.0
4      Gayle  4528000.0
5       Adam  4528000.0
6     Rooter  7028000.0
7   Peterson  2528000.0
8      lynda        NaN
9        NaN        NaN
10     Jenny    25632.0
11      Kenn    25632.0
12       Aly    25582.0
13      John  1528000.0
14       Ali        NaN

In [ ]:
# handling and manuplating DF columns
- 'df.columns' - give us a series of the column names
- 'df.columns[n]' - get specific column names using index number
- 'df.columns[[0, 2, 5]]' - get multi columns based on multi indexes

In [30]:
print(cars_df.columns[0])
print(cars_df.columns[[0, 2, 5]])

Car
Index(['Car', 'Cylinders', 'Weight'], dtype='str')

In [31]:
print(cars_df['Car'])

0                  Chevrolet Vega
1             Chevrolet Vega (sw)
2             Chevrolet Vega 2300
3                 Chevrolet Woody
4      Chevrolete Chevelle Malibu
                  ...
156              Mercury Capri v6
157       Mercury Cougar Brougham
158         Mercury Grand Marquis
159                Mercury Lynx l
160               Mercury Marquis
Name: Car, Length: 161, dtype: str

In [32]:
print(cars_df.head())
subset = cars_df[['MPG', 'Cylinders', 'Displacement', 'Weight']]

                          Car   MPG  Cylinders  Displacement  Horsepower  \
0              Chevrolet Vega  25.0          4         140.0          75
1         Chevrolet Vega (sw)  22.0          4         140.0          72
2         Chevrolet Vega 2300  28.0          4         140.0          90
3             Chevrolet Woody  24.5          4          98.0          60
4  Chevrolete Chevelle Malibu  16.0          6         250.0         105

   Weight  Acceleration  Model Origin  quantity     city
0    2542          17.0     74     US       177       NJ
1    2408          19.0     71     US        91   DALLAS
2    2264          15.5     71     US        74    TEXAS
3    2164          22.1     76     US       241       OH
4    3897          18.5     75     US       206  NewYork

In [33]:
print(cars_df.head())

                          Car   MPG  Cylinders  Displacement  Horsepower  \
0              Chevrolet Vega  25.0          4         140.0          75
1         Chevrolet Vega (sw)  22.0          4         140.0          72
2         Chevrolet Vega 2300  28.0          4         140.0          90
3             Chevrolet Woody  24.5          4          98.0          60
4  Chevrolete Chevelle Malibu  16.0          6         250.0         105

   Weight  Acceleration  Model Origin  quantity     city
0    2542          17.0     74     US       177       NJ
1    2408          19.0     71     US        91   DALLAS
2    2264          15.5     71     US        74    TEXAS
3    2164          22.1     76     US       241       OH
4    3897          18.5     75     US       206  NewYork

In [34]:
print(cars_df.Car.values.unique())

<StringArray>
[            'Chevrolet Vega',        'Chevrolet Vega (sw)',
        'Chevrolet Vega 2300',            'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',                  'Chevy C20',
                 'Chevy S-10',           'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',     'Chrysler Lebaron Salon',
 ...
              'Mazda RX-7 GS',         'Mercedes Benz 300d',
         'Mercedes-Benz 240d',         'Mercedes-Benz 280s',
         'Mercury Capri 2000',           'Mercury Capri v6',
    'Mercury Cougar Brougham',      'Mercury Grand Marquis',
             'Mercury Lynx l',            'Mercury Marquis']
Length: 132, dtype: str

In [35]:
print(cars_df[cars_df.columns[0]].values)

<StringArray>
[            'Chevrolet Vega',        'Chevrolet Vega (sw)',
        'Chevrolet Vega 2300',            'Chevrolet Woody',
 'Chevrolete Chevelle Malibu',                  'Chevy C20',
                 'Chevy S-10',           'Chrysler Cordoba',
 'Chrysler Lebaron Medallion',     'Chrysler Lebaron Salon',
 ...
              'Mazda RX-7 GS',         'Mercedes Benz 300d',
         'Mercedes-Benz 240d',         'Mercedes-Benz 280s',
         'Mercury Capri 2000',           'Mercury Capri v6',
    'Mercury Cougar Brougham',      'Mercury Grand Marquis',
             'Mercury Lynx l',            'Mercury Marquis']
Length: 161, dtype: str

In [36]:
index_list = cars_df.index.tolist()
print(index_list)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160]

In [37]:
cars_df['ID'] = index_list
cars_df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ,0
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS,1
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS,2
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH,3
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork,4

In [ ]:
# sorting with DF
# df.sort_values(by, ascending)
#

In [38]:
cars_df.sort_values(by='Horsepower', ascending=False)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
79,Ford F250,10.0,8,360.0,215,4615,14.0,70,US,69,NJ,79
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork,11
56,Dodge D200,11.0,8,318.0,210,4382,13.5,70,US,71,NJ,56
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH,160
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ,5
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Mazda GLC Deluxe,32.8,4,78.0,52,1985,19.4,78,Japan,291,NewYork,146
68,Fiat 128,29.0,4,68.0,49,1867,19.5,73,Europe,162,TEXAS,68
109,Ford Mustang Cobra,23.6,4,140.0,0,2905,14.3,80,US,381,TEXAS,109
104,Ford Maverick,21.0,6,200.0,0,2875,17.0,74,US,171,TEXAS,104
113,Ford Pinto,25.0,4,98.0,0,2046,19.0,71,US,76,DALLAS,113

In [39]:
cars_df

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ,0
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS,1
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS,2
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH,3
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork,4
...,...,...,...,...,...,...,...,...,...,...,...,...
156,Mercury Capri v6,21.0,6,155.0,107,2472,14.0,73,US,158,NewYork,156
157,Mercury Cougar Brougham,15.0,8,302.0,130,4295,14.9,77,US,27,NJ,157
158,Mercury Grand Marquis,16.5,8,351.0,138,3955,13.2,79,US,332,DALLAS,158
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS,159
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH,160

In [40]:
cars_df.sort_values(by='Acceleration', ascending=False)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH,3
153,Mercedes-Benz 240d,30.0,4,146.0,67,3250,21.8,80,Europe,373,DALLAS,153
96,Ford Grenada ghia,18.0,6,250.0,78,3574,21.0,76,US,245,NewYork,96
76,Ford Escort 2H,29.9,4,98.0,65,2380,20.7,81,US,397,NJ,76
152,Mercedes Benz 300d,25.4,5,183.0,77,3530,20.1,79,Europe,342,NJ,152
...,...,...,...,...,...,...,...,...,...,...,...,...
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH,160
123,Ford Torino,17.0,8,302.0,140,3449,10.5,70,US,5,OH,123
43,Dodge Challenger SE,15.0,8,383.0,170,3563,10.0,70,US,67,DALLAS,43
87,Ford Galaxie 500,15.0,8,429.0,198,4341,10.0,70,US,8,OH,87
108,Ford Mustang Boss 302,0.0,8,302.0,140,3353,8.0,70,US,75,DALLAS,108

In [44]:

# sort by both horsepower and acceleration
cars_df.sort_values(by=['Horsepower', 'Acceleration'], ascending=[False, True])

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork,11
79,Ford F250,10.0,8,360.0,215,4615,14.0,70,US,69,NJ,79
56,Dodge D200,11.0,8,318.0,210,4382,13.5,70,US,71,NJ,56
160,Mercury Marquis,11.0,8,429.0,208,4633,11.0,72,US,112,OH,160
5,Chevy C20,10.0,8,307.0,200,4376,15.0,70,US,70,NJ,5
...,...,...,...,...,...,...,...,...,...,...,...,...
146,Mazda GLC Deluxe,32.8,4,78.0,52,1985,19.4,78,Japan,291,NewYork,146
68,Fiat 128,29.0,4,68.0,49,1867,19.5,73,Europe,162,TEXAS,68
109,Ford Mustang Cobra,23.6,4,140.0,0,2905,14.3,80,US,381,TEXAS,109
104,Ford Maverick,21.0,6,200.0,0,2875,17.0,74,US,171,TEXAS,104
113,Ford Pinto,25.0,4,98.0,0,2046,19.0,71,US,76,DALLAS,113

In [45]:
cars_df.sort_values(by='MPG', ascending=False)

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city,ID
142,Mazda GLC,46.6,4,86.0,65,2110,17.9,80,Japan,367,NJ,142
136,Honda Civic 1500 gl,44.6,4,91.0,67,1850,13.8,80,Japan,374,NewYork,136
18,Datsun 210,40.8,4,85.0,65,2110,19.2,80,Japan,369,DALLAS,18
33,Datsun B210 GX,39.4,4,85.0,70,2070,18.6,78,Japan,292,DALLAS,33
133,Honda Civic,38.0,4,91.0,67,1965,15.0,82,Japan,82,DALLAS,133
...,...,...,...,...,...,...,...,...,...,...,...,...
79,Ford F250,10.0,8,360.0,215,4615,14.0,70,US,69,NJ,79
126,Hi 1200D,9.0,8,304.0,193,4732,18.5,70,US,72,DALLAS,126
13,Citroen DS-21 Pallas,0.0,4,133.0,115,3090,17.5,70,Europe,58,DALLAS,13
124,Ford Torino (sw),0.0,8,351.0,153,4034,11.0,70,US,56,NewYork,124
108,Ford Mustang Boss 302,0.0,8,302.0,140,3353,8.0,70,US,75,DALLAS,108

In [ ]:
# Slicing a DataFrame
- pull out specific parts of a dataframe 
- to examin a subset, remove unwanted / unneeded data
data isolation, removal of clutter
- 'df[[cols1, col2, col3, col4]]' - slicing using double square bracket synthax

In [46]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['John', 41, 85, 1528000],

]
columns = ['Name', 'Age', 'Weight (KGs)', 'Salary']
df = pd.DataFrame(employee_list, columns=columns)
print(df.head())

      Name  Age  Weight (KGs)   Salary
0    James   36            75  5428000
1  Villers   38            74  3428000
2    VKole   31            70  8428000
3    Smith   34            80  4428000
4    Gayle   40           100  4528000

In [ ]:
# slicing Functions
- 'df.loc[]' - label based location (column names to locate and slice)
- 'df.iloc[start:stop:step (rows) , start:stop:step (cols)]' - index based location (index numbers to locate and slice)
- with the python indexing operator. STOP IS ALWAYS NON_INCLUSIVE

In [47]:
# python indexing operator
emp_subset = df.iloc[ : , 0:2]
print(emp_subset)

       Name  Age
0     James   36
1   Villers   38
2     VKole   31
3     Smith   34
4     Gayle   40
5    Rooter   33
6  Peterson   42
7      John   41

In [48]:
# using iloc, how can you grab the first 2 records of the first 2 columns
emp_sub_subset = df.iloc[0:2, 0:2]
print(emp_sub_subset)

      Name  Age
0    James   36
1  Villers   38

In [49]:
# use a list in the column argument to specificy specific lists
print(df.iloc[:, [0, 2, 3]])

       Name  Weight (KGs)   Salary
0     James            75  5428000
1   Villers            74  3428000
2     VKole            70  8428000
3     Smith            80  4428000
4     Gayle           100  4528000
5    Rooter            72  7028000
6  Peterson            85  2528000
7      John            85  1528000

In [50]:
#create DataFrame with six columns
df = pd.DataFrame(
    {'team': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H'],
                   'points': [18, 22, 19, 14, 14, 11, 20, 28],
                   'assists': [5, 7, 7, 9, 12, 9, 9, 4],
                   'rebounds': [11, 8, 10, 6, 6, 5, 9, 12],
                   'steals': [4, 3, 3, 2, 5, 4, 3, 8],
                   'blocks': [1, 0, 0, 3, 2, 2, 1, 5]}
    )

In [ ]:
# correct this 
- 'df.loc[]' - label based location (column names to locate and slice)
- 'df.iloc[start:stop:step (rows) , start:stop:step (cols)]' - index based location

In [51]:
print(df.head())

  team  points  assists  rebounds  steals  blocks
0    A      18        5        11       4       1
1    B      22        7         8       3       0
2    C      19        7        10       3       0
3    D      14        9         6       2       3
4    E      14       12         6       5       2

In [52]:
# grab all rows, and only the team and rebounds cols
print(df.loc[:, ['team', 'rebounds']])

  team  rebounds
0    A        11
1    B         8
2    C        10
3    D         6
4    E         6
5    F         5
6    G         9
7    H        12

In [53]:
# grab all rows, and columns starting from team to rebounds
print(df.loc[:, 'team':'rebounds'])

  team  points  assists  rebounds
0    A      18        5        11
1    B      22        7         8
2    C      19        7        10
3    D      14        9         6
4    E      14       12         6
5    F      11        9         5
6    G      20        9         9
7    H      28        4        12

In [54]:
print(df.loc[3:6, 'team'])

3    D
4    E
5    F
6    G
Name: team, dtype: str

In [55]:
print(df.loc[3:6, ['team']])

  team
3    D
4    E
5    F
6    G

In [ ]:
# slicing with square bracket synthax
- 'df[colName']' - single column
- 'df[[col1', 'col2', 'col3']]' - multi column select, with label 
- 'df[n]' - slecting with index number
- 'df[[1, 2, 3, 4, 5]]' - multi select with index number'df[condition]' - filter rows based on a condition

In [58]:
df = pd.read_json('data/cars.json')
df.head()

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
0,Chevrolet Vega,25.0,4,140.0,75,2542,17.0,74,US,177,NJ
1,Chevrolet Vega (sw),22.0,4,140.0,72,2408,19.0,71,US,91,DALLAS
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
3,Chevrolet Woody,24.5,4,98.0,60,2164,22.1,76,US,241,OH
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork

In [ ]:
df[[]]

In [59]:
# find all records that have MPG equal to 17.6 >, <, ==, !=
print(df[ df['MPG'] == 17.6])

                        Car   MPG  Cylinders  Displacement  Horsepower  \
9    Chrysler Lebaron Salon  17.6          6         225.0          85
101         Ford LTD Landau  17.6          8         302.0         129

     Weight  Acceleration  Model Origin  quantity     city
9      3465          16.6     81     US       412    TEXAS
101    3725          13.4     79     US       331  NewYork

In [62]:
# find all records that have MPG equal to 17.6
df['MPG'] == 17.6
df[ df['MPG'] == 17.6]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
101,Ford LTD Landau,17.6,8,302.0,129,3725,13.4,79,US,331,NewYork

In [ ]:
df[ df['Horsepower'] > 100]
df[df['Horsepower'].gt(100)]

In [72]:
# get cars that have a quality over 350 and cylinders less than 4
# multiple conditions - & = and, | as or
df[(df['quantity'] > 350) & (df['Cylinders'] < 4)]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
151,Mazda RX-7 GS,23.7,3,70.0,100,2420,12.5,80,Japan,379,NewYork

In [ ]:
# NewYork or New York
df[(df['city'] == 'New York') | (df['city'] == 'NewYork')]

In [75]:
df[df['city'].isin(['NewYork', 'TEXAS'])]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
2,Chevrolet Vega 2300,28.0,4,140.0,90,2264,15.5,71,US,74,TEXAS
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
6,Chevy S-10,31.0,4,119.0,82,2720,19.4,82,US,7,NewYork
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
...,...,...,...,...,...,...,...,...,...,...,...
150,Mazda RX-4,21.5,3,80.0,110,2720,13.5,77,Japan,288,NewYork
151,Mazda RX-7 GS,23.7,3,70.0,100,2420,12.5,80,Japan,379,NewYork
154,Mercedes-Benz 280s,16.5,6,168.0,120,3820,16.7,76,Europe,256,TEXAS
156,Mercury Capri v6,21.0,6,155.0,107,2472,14.0,73,US,158,NewYork
159,Mercury Lynx l,36.0,4,98.0,70,2125,17.3,82,US,425,TEXAS

In [ ]:
# Pandas string functions for filtering
- 'df.col.str.contains()'
- 'df.col.str.startswith()'
- 'df.col.str.endswith()'
- 'df.col.str.len()'
- 'df.col.str.upper()'
- 'df.col.str.lower()'
- 'df.col.str.title()'
- 'df.col.str.split()'

In [76]:
df[df['Car'].str.endswith('m')]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
50,Dodge Colt Hatchback Custom,35.7,4,98.0,80,1915,14.4,79,US,340,NewYork
51,Dodge Colt m/m,33.5,4,98.0,83,2075,15.9,77,US,283,NJ
52,Dodge Coronet Brougham,16.0,8,318.0,150,4190,13.0,76,US,233,DALLAS
53,Dodge Coronet Custom,15.0,8,318.0,150,3777,12.5,73,US,134,TEXAS
57,Dodge Dart Custom,15.0,8,318.0,150,3399,11.0,73,US,166,DALLAS
61,Dodge Monaco Brougham,15.5,8,318.0,145,4140,13.7,77,US,268,NJ
71,Fiat Strada Custom,37.3,4,91.0,69,2130,14.7,79,Europe,349,NJ
144,Mazda GLC Custom,31.0,4,91.0,68,1970,17.6,82,Japan,423,TEXAS
157,Mercury Cougar Brougham,15.0,8,302.0,130,4295,14.9,77,US,27,NJ

In [77]:
df[df['Car'].str.len() > 20]

,Car,MPG,Cylinders,Displacement,Horsepower,Weight,Acceleration,Model,Origin,quantity,city
4,Chevrolete Chevelle Malibu,16.0,6,250.0,105,3897,18.5,75,US,206,NewYork
8,Chrysler Lebaron Medallion,26.0,4,156.0,92,2585,14.5,82,US,434,DALLAS
9,Chrysler Lebaron Salon,17.6,6,225.0,85,3465,16.6,81,US,412,TEXAS
10,Chrysler Lebaron Town @ Country (sw),18.5,8,360.0,150,3940,13.0,79,US,337,OH
11,Chrysler New Yorker Brougham,13.0,8,440.0,215,4735,11.0,73,US,139,NewYork
12,Chrysler Newport Royal,13.0,8,400.0,190,4422,12.5,72,US,115,NJ
34,Datsun F-10 Hatchback,33.5,4,85.0,70,1945,16.8,77,Japan,265,TEXAS
38,Dodge Aries Wagon (sw),25.8,4,156.0,92,2620,14.4,81,US,385,DALLAS
50,Dodge Colt Hatchback Custom,35.7,4,98.0,80,1915,14.4,79,US,340,NewYork
52,Dodge Coronet Brougham,16.0,8,318.0,150,4190,13.0,76,US,233,DALLAS
54,Dodge Coronet Custom (sw),14.0,8,318.0,150,4457,13.5,74,US,183,OH
61,Dodge Monaco Brougham,15.5,8,318.0,145,4140,13.7,77,US,268,NJ
74,Ford Country Squire (sw),13.0,8,400.0,170,4746,12.0,71,US,88,OH
75,Ford Country Squire (sw),15.5,8,351.0,142,4054,14.3,79,US,335,NewYork
93,Ford Gran Torino (sw),13.0,8,302.0,140,4294,16.0,72,US,119,NewYork
94,Ford Gran Torino (sw),14.0,8,302.0,140,4638,16.0,74,US,184,NJ
108,Ford Mustang Boss 302,0.0,8,302.0,140,3353,8.0,70,US,75,DALLAS
157,Mercury Cougar Brougham,15.0,8,302.0,130,4295,14.9,77,US,27,NJ
158,Mercury Grand Marquis,16.5,8,351.0,138,3955,13.2,79,US,332,DALLAS

In [ ]:
# Dealing with Nan
- np.nan
- dropna

In [78]:
# Initializing the nested list with Data set
employee_list = [['James', 36, 75, 5428000],
               ['Villers', 38, 74, 3428000],
               ['VKole', 31, 70, 8428000],
               ['Smith', 34, 80, 4428000],
               ['Gayle', 40, 100, 4528000],
               ['Adam', 40, np.nan, 4528000],
               ['Rooter', 33, 72, 7028000],
               ['Peterson', 42, 85, 2528000],
               ['lynda', 42, 85, np.nan],
               [np.nan, 42, 85, np.nan],
               ['Jenny', np.nan, 100, 25632],
               ['Kenn', np.nan, 110, 25632],
                ['Aly', np.nan, 90, 25582],
               ['John', 41, 85, 1528000]]
               
columns=['Name', 'Age', 'Weight', 'Salary']
df = pd.DataFrame(employee_list, columns=columns)
df.head()

      Name   Age  Weight     Salary
0    James  36.0    75.0  5428000.0
1  Villers  38.0    74.0  3428000.0
2    VKole  31.0    70.0  8428000.0
3    Smith  34.0    80.0  4428000.0
4    Gayle  40.0   100.0  4528000.0

In [79]:
print(f'Missing Vals: \n{df.isnull().sum()}')

Missing Vals:
Name      1
Age       3
Weight    1
Salary    2
dtype: int64

In [80]:
df_clean = df.dropna()

print(f'Missing Vals: \n{df.isnull().sum()}')

Missing Vals:
Name      1
Age       3
Weight    1
Salary    2
dtype: int64